name: Typescript
description: Performs typescript checks
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - run: npm run lint
      shell: sh
    - run: npm run test:types
      shell: sh
