name: Unit
description: Performs unit tests checks
runs:
  using: composite
  steps:
    - run: npm run build
      shell: sh
    - run: npm -w packages/core test
      shell: sh
    - run: npm -w packages/dom test
      shell: sh
    - run: npm -w packages/react-dom test
      shell: sh
    - run: npm -w packages/react-dom-interactions test
      shell: sh
