import getScrollParent from './getScrollParent';
import getTotalScroll from './getTotalScroll';
import getParentNode from './getParentNode';
import findCommonOffsetParent from './findCommonOffsetParent';
import getOffsetRectRelativeToArbitraryNode from './getOffsetRectRelativeToArbitraryNode';
import getOffsetRectRelativeToViewport from './getOffsetRectRelativeToViewport';
import getWindowSizes from './getWindowSizes';
import isFixed from './isFixed';

/**
 * Computed the boundaries limits and return them
 * @method
 * @memberof Popper.Utils
 * @param {Object} data - Object containing the property "offsets" generated by `_getOffsets`
 * @param {Number} padding - Boundaries padding
 * @param {Element} boundariesElement - Element used to define the boundaries
 * @returns {Object} Coordinates of the boundaries
 */
export default function getBoundaries(popper, reference, padding, boundariesElement) {
    // NOTE: 1 DOM access here
    let boundaries = { top: 0, left: 0 };
    const offsetParent = findCommonOffsetParent(popper, reference);

    // Handle viewport case
    if (boundariesElement === 'viewport') {
        const { left, top } = getOffsetRectRelativeToViewport(offsetParent);
        const { clientWidth: width, clientHeight: height } = window.document.documentElement;
        const scrollLeft = getTotalScroll(popper, offsetParent, 'left');
        const scrollTop = getTotalScroll(popper, offsetParent, 'top');

        boundaries = {
            top: 0 - top + scrollTop,
            right: width - left + scrollLeft,
            bottom: height - top + scrollTop,
            left: 0 - left + scrollLeft,
        };
    }
    // Handle other cases based on DOM element used as boundaries
    else {
        let boundariesNode;
        if (boundariesElement === 'scrollParent') {
            boundariesNode = getScrollParent(getParentNode(popper));
            if (boundariesNode.nodeName === 'BODY') {
                boundariesNode = window.document.documentElement;
            }
        } else if (boundariesElement === 'window') {
            boundariesNode = window.document.documentElement;
        } else {
            boundariesNode = boundariesElement;
        }

        // In case of HTML, we need a different computation
        if (boundariesNode.nodeName === 'HTML' && !isFixed(offsetParent)) {
            const { height, width } = getWindowSizes();
            boundaries.right = width;
            boundaries.bottom = height;
        }
        // for all the other DOM elements, this one is good
        else {
            boundaries = getOffsetRectRelativeToArbitraryNode(boundariesNode, offsetParent);
        }
    }

    // Add paddings
    boundaries.left += padding;
    boundaries.top += padding;
    boundaries.right -= padding;
    boundaries.bottom -= padding;

    return boundaries;
}
