/**
 * Modifier used to hide the popper when its reference element is outside of the
 * popper boundaries. It will set `style.display = 'none'` to hide it, and `style.display = ''`
 * to restore its initial display value.
 * @method
 * @memberof Modifiers
 * @argument {Object} data - The data object generated by update method
 * @argument {Object} options - Modifiers configuration and options
 * @returns {Object} The data object, properly modified
 */
export default function hide(data) {
    const refRect = data.offsets.reference;
    const bound = data.boundaries;

    if (
        refRect.bottom < bound.top ||
        refRect.left > bound.right ||
        refRect.top > bound.bottom ||
        refRect.right < bound.left
    ) {
        data.styles.display = 'none';
    } else {
        data.styles.display = '';
    }

    return data;
}
