name: Functional
description: Performs functional tests checks
runs:
  using: composite
  steps:
    - run: npx playwright install --with-deps chromium
      shell: sh
    - run: pnpm run playwright
      shell: sh
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: visual-snapshots-diff
        path: packages/dom/test-results
